[package]
org = "ballerina"
name = "data.text"
version = "0.1.0"
distribution = "2201.12.0"
authors = ["Ballerina"]
keywords = ["text", "data", "string", "processing"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.text"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.text-native"
version = "0.1.0"
path = "../native/build/libs/data.text-native-0.1.0.jar"
